### ISSUE TITLE
about dwell in squiggle output

### ISSUE THREAD

**Issue by Angelven** [nanoporetech/scrappie#15]
Hi, 
  A small question about the squiggle output format, what does the five column "Dwell (samples)" mean ? Does it mean the current length for each base ?

**Comment by tmassingham-ont** [comment]
Hello.  On average we would expect that state to last 'Dwell' number of samples; sampling occurs at 4kHz for the current DNA chemistry but this may change in the future.

Note: The squiggler outputs a base to help with registration and interpretation but you should be careful in identifying the current level reported with an individual base since the signal is dependent on a wide sequence context.

**Comment by Angelven** [comment]
what do you mean by ‘Dwell’ number of sample ? To plot a current profile for sequencing reads, I need to know the current signal and time duration of current for each base. I think from the squiggle output, I can get the normalized current for each base, but how can I get the time duration of current for each base ?

**Comment by tmassingham-ont** [comment]
Sorry for the lack of clarity.  The 'dwell' _is_ the length of time spent in each state, measure in samples rather than seconds.  To a get a time in second, divide by the sample rate (currently 4kHz for DNA, 6kHz for RNA).

**Comment by Angelven** [comment]
Got it ! Thanks very much
