### ISSUE TITLE
Homopolymer Accuracy Scrappie vs. Albacore

### ISSUE THREAD

**Issue by damientully** [nanoporetech/scrappie#16]
I just tried Scrappie on a bunch of reads that were also basecalled with Albacore v2.1.2 and then de novo assembled a genome using Canu and compared it against the known reference. Before any polishing the data from Albacore gave me a consensus that was 98.9% identical while Scrappie gave a slightly improved 99.08% consensus. All of the differences are in homopolymer regions and while Scrappie did obviously improve some calls it also undercalled a number of homopolymer in comparison to Albacore. If you merge the both assemblies and cherry pick the best parts of each you get a 99.3% agreement pre-polishing. Can you clarify the hompolymer differences between Scrappie and Albacore and how they differ in this respect as I thought that the best bits of Scrappie were already in Albacore? Thanks!

**Comment by tmassingham-ont** [comment]
Hello.  It's not surprising that Scrappie and Albacore give slightly different results since they are different implementations of the same techniques but differ in some of the details, like how they trim and scale reads, and also in the coefficients of the models used.
Improving consensus accuracy being actively worked on at the moment and we're looking closely at how implementation details affect the final result -- tiny differences become important when you are trying to squash errors that occur every tens of thousands of bases.  Observations like yours show there is a lot of gain to be had from getting the algorithms right -- hopefully we can get the best of both without cherry-picking :-)

Thanks.
