### ISSUE TITLE
Fastq output?

### ISSUE THREAD

**Issue by rybern** [nanoporetech/scrappie#26]
Hi,

I'm wondering how difficult it would be to add fastq output to Scrappie raw/events. I can probably help implement this.

I see that Nanonet derives quality scores here: https://github.com/ProgramFiles/nanonet/blob/master/nanonet/nanonetcall.py#L195 lines 195-274. Can analogous code be written for Scrappie?

Thanks,
Ryan

**Comment by tmassingham-ont** [comment]
That's a very generous offer but not outputting quality information from Scrappie was a design decision.

In common to every other sequencing platform, quality scores need to calibrated before they are meaningful and we don't want Scrappie to produce potentially misleading scores.  The purpose of Scrappie is to demonstrate improvements in accuracy, rather than being a complete solution, so the additional work to calibrate quality scores is outside the scope of the project.

That said, quality scores are planned for Flappie, the successor to Scrappie.
