### ISSUE TITLE
Failed find read name under /Raw/Reads/.

### ISSUE THREAD

**Issue by wangxinbio** [nanoporetech/scrappie#31]
Hi 
When I use the scrappie on my data. It showed an error 
scrappie: Failed find read name under /Raw/Reads/.
scrappie: No basecall returned for PAD32967_5954ef99b0ae76a55a24e4c16f51c7cf779f777a_10.fast5

But when I used this command on test data in scrappie, it is fine.

How can I fix it ?

my command is 
scrappie raw PAD32967_5954ef99b0ae76a55a24e4c16f51c7cf779f777a_10.fast5  > test.fa

**Comment by tmassingham-ont** [comment]
Hello. This is likely due to trying to use `multi-read` fast5 with `flappie`.

Presently, both `flappie` and `scrappie` only support the older single-read fast5 format. The work-around is convert the reads using the `multi_to_single_fast5` tool from the `ont-fast5-api` package (see https://github.com/nanoporetech/flappie/issues/25).

Sorry for the inconvenience.
