### ISSUE TITLE
Problem building on Ubuntu 12.04

### ISSUE THREAD

**Issue by rrwick** [nanoporetech/scrappie#5]
Hi!

When I tried to build Scrappie v1.1.0 on Ubuntu 12.04, it didn't work due to `aligned_alloc` not being defined. A bit of Googling indicated that this is because Ubuntu 12.04 has glibc v2.15 and that function was added in v2.16. So close!

I managed to make scrappie work with a crude hack: I replaced the two instances of `aligned_alloc` in `scrappie_matrix.c` with `posix_memalign` calls instead:
```diff
34c34,36
<     mat->data.v = aligned_alloc(16, nrq * nc * sizeof(__m128));
---
>     void *result;
>     if (posix_memalign(&result, 16, nrq * nc * sizeof(__m128))) result = 0;
>     mat->data.v = result;
279c281,283
<     mat->data.v = aligned_alloc(16, nrq * nc * sizeof(__m128i));
---
>     void *result;
>     if (posix_memalign(&result, 16, nrq * nc * sizeof(__m128i))) result = 0;
>     mat->data.v = result;
```

I'll close this issue now because I got it working - hopefully if anyone else hits the same problem they can try my fix. Whether or not this should be changed in Scrappie so it supports old Ubuntu versions... well that's up to you!

Ryan

**Comment by tmassingham-ont** [comment]
Hello.  Yes, that's a valid solution.  We used use `posix_memalign` but moved to  `aligned_alloc`  for two reasons:

1.  It is part of the C11 standard library.
2. On the systems we tested, `posix_memalign` was implemented as a macro and this interfered with our Q&D memory validator (the gross details: if 'CHAOS' is defined, all memory allocation routines are wrapped such that they random return NULL and we can test that the program fails gracefully).

Thanks for posting your diff so that others may benefit.

TimM.
